name: Cleanup PR Environments

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete GitHub Environment
        run: |
          echo "REF: ${{ github.event.ref }}"
          echo "REF TYPE: ${{ github.event.ref_type }}"
          gh api /repos/${{ github.repository }}/environments
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}